### ISSUE TITLE
Possible screenshot replacement needed for Cancer Data Service Explorer at Seven Bridges

### ISSUE THREAD

**Issue by vthorsson** [ncihtan/htan_missing_manual#1]
May need to edit `access_conrolled/cds_seven_bridges' it seems Seven Bridges is not listing by dataset such as HTAN but instead by phs accession number PHS002371 is HTAN 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/2837859/206023014-f0b3957f-1b73-49d8-b191-fd2e5cc3efc9.png">

**Comment by clarisse-lau** [comment]
Closing as SB-CGC added the Dataset filter back in
