### ISSUE TITLE
Add ID-Provenance figure

### ISSUE THREAD

**Issue by PozhidayevaDarya** [ncihtan/htan_missing_manual#3]
Would it be possible/useful to add in the ID provenance figure that we've developed?
I think it can go in a general description or BQ section:

Full image:
https://docs.google.com/presentation/d/1SGzh1F2C-w2MaDU1AR-DHjPd0zGn8-pz/edit#slide=id.p1
Slide sized image:
https://docs.google.com/presentation/d/1iBQYHGCZ8F9CKLyQU3P6CSPm6chsUSPJzjk-JZLoHlM/edit#slide=id.p

**Comment by ecerami** [comment]
Reassigning to @Gibbsdavidl, as he has volunteered to make the next batch of manual edits.

**Comment by Gibbsdavidl** [comment]
Yep! Updates are in progress ... We've added this image.
