### ISSUE TITLE
Need to update https://docs.humantumoratlas.org/overview/centers/

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan_missing_manual#38]
Once we have finalized the new HTAN IDs for Phase 2, we should update this page:  https://docs.humantumoratlas.org/overview/centers/

It should include Phase 2 centers, followed by Phase 1 centers.

This page also links to the portal network page, and I have separately logged an issue to update that page as well.

**Comment by jen-dfci** [comment]
Added new centers to current PR#36 which also includes liaison page updates.  Once IDs are finalized, this can be merged.

**Comment by jen-dfci** [comment]
PR#36 merged with new centers on HTAN Centers and Data Liaisons pages.
