### ISSUE TITLE
New Page for Creating HTAN Identifiers

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan_missing_manual#42]
Currently, the page:  https://docs.humantumoratlas.org/data_model/identifiers/

has information directed at external users and information directed at data submitters.

I think it might be more clear if this page was just focussed on external users, and then we create a new page under the "Submitting Data" section, called "Creating HTAN Identifiers" that contains all the text for that.

@jen-dfci thoughts?

**Comment by jen-dfci** [comment]
That's a good idea.  I can split this and might add a link from data_model/identifiers to a new 'creating identifiers' page.

**Comment by ecerami** [comment]
thanks.

**Comment by jen-dfci** [comment]
PR#47

**Comment by ecerami** [comment]
Done!
