### ISSUE TITLE
New Intro Page for Submitting Data Section

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan_missing_manual#44]
Small suggestion, in the "Submitting Data" section, I would suggest a new "Intro" page that explicitly states that this is for HTAN centers that will submit data.

This way, an external user is not confused and can easily skip this entire section.

**Comment by jen-dfci** [comment]
Would moving the "Data Submission Overview" page to the top of that section work/renaming it "Introduction"?

**Comment by ecerami** [comment]
oh I see, yes that would work too.

**Comment by jen-dfci** [comment]
Great!  - I will make that change.

**Comment by ecerami** [comment]
Done!
