### ISSUE TITLE
Data De-Identification page - remove ref to de-id plan

### ISSUE THREAD

**Issue by aclayton555** [ncihtan/htan_missing_manual#59]
In the Data De-Identification page (https://docs.humantumoratlas.org/data_submission/data_deidentification/), suggest that we also remove the reference and link to the de-ID plan, to align with edits to Step 5 of the checklist in https://github.com/ncihtan/htan_missing_manual/pull/58/files

Current: 

> New HTAN Centers should develop and submit a De-identification Plan using the [HTAN Atlas De-Identification Plan Template](https://docs.google.com/document/d/1jFXYVMhLEGVcMNBh3L-U1rr4B-KLG7gK-ETc1SzMHhs/edit?usp=sharing).
> 
> Prior to transferring data to the HTAN DCC, members are responsible for fully de-identifying the data being transferred. Full de-identification of data includes confirmation that data file names do not contain any information that could be used to re-identify that data subject.

Suggested edit:

> Prior to transferring data to the HTAN DCC, members are responsible for fully de-identifying the data being transferred. Full de-identification of data includes confirmation that data file names do not contain any information that could be used to re-identify that data subject. Please review your Center’s responsibilities for [Data De-identification](https://docs.humantumoratlas.org/data_submission/data_deidentification/) and make sure to have a disussion with your data liaison on this topic.

**Comment by jen-dfci** [comment]
removed in PR#61
